CREATE DATABASE fullstack_collaborators;
\c fullstack_collaborators;
CREATE TABLE fullstack_collaborators (name varchar, language varchar, contact int, role varchar, id PRIMARY KEY;

CREATE DATABASE fullstack;
\c fullstack;
CREATE TABLE fullstack (name varchar, owner varchar, owner_contact varchar, id PRIMARY KEY;

CREATE DATABASE geek_collaborators;

\c geek_collaborators;


CREATE TABLE contacts(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    email VARCHAR,
    subject VARCHAR,
    message VARCHAR
);

CREATE DATABASE geek_collaborators_test WITH TEMPLATE geek_collaborators;

