CREATE DATABASE geek_collaborators;
\c geek_collaborators;

CREATE TABLE contacts(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    email VARCHAR,
    subject VARCHAR,
    message VARCHAR
);

CREATE TABLE jobs (
id SERIAL PRIMARY KEY,
company VARCHAR,
title VARCHAR,
description VARCHAR,
duration VARCHAR,
languages VARCHAR
);

CREATE TABLE students (
id SERIAL PRIMARY KEY,
name VARCHAR,
email VARCHAR,
password VARCHAR
);

CREATE TABLE developers (
id SERIAL PRIMARY KEY,
name VARCHAR,
email VARCHAR,
password VARCHAR,
);

CREATE TABLE collaboration (
id SERIAL PRIMARY KEY,
username VARCHAR,
resume VARCHAR,
project_code VARCHAR,
date date
);

CREATE TABLE contacts(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    email VARCHAR,
    subject VARCHAR,
    message VARCHAR
);

CREATE TABLE fullstack_collaborators (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar,
language varchar,
contact int,
role varchar
);

CREATE TABLE fullstack (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar,
 owner varchar,
 owner_contact varchar
);

CREATE DATABASE geek_collaborators_test WITH TEMPLATE geek_collaborators;

